<?php


class Customer_service_detail_model extends MY_Model
{

    var $_table ="customer_service_detail";

    function get($primary_value)
    {
        $this->has_one['item'] = array('ItemId','ItemId',"$this->_table.*,item.ItemCode,item.ItemName");
        $this->join('item');
        return parent::get($primary_value); // TODO: Change the autogenerated stub
    }

    public function get_many_by()
    {
        $this->load->model("Item_model","Item_model_model");
        $item = $this->Item_model_model->table();
        $this->db->join($item,"$item.ItemId = $this->_table.ItemId");
        $this->db->select("$this->_table.*,item.ItemCode,item.ItemName");
        $where = func_get_args();
        $this->_set_where($where);

        return $this->get_all();
    }

}