<?php

class Joborder_model  extends MY_Model
{
    protected $_table = 'job_order';
    protected $primary_key = 'JobOrderId';

    protected $before_create = ['prop_data_before_create'] ;
    protected $after_create = ['prop_data_after_create'] ;
    protected $before_update = ['prop_data_before_update'] ;

    var $belongs_to = [
        "Customer" => ["model"=>"Customer_model","primary_key"=>"CustomerId"],
        "Item" => ["model"=>"item_model","primary_key"=>"ItemId"],
        "Repair" => ["model"=>"Repair_mode_model","primary_key"=>"RepairModeId"],
        "Close" => ["model"=>"Job_order_close_model","primary_key"=>"JobOrderId"]
    ];
    var $belongs_with = [
        "JOB_TO_TECH" => ["model"=>"Job_order_technician_model","key"=>"JobOrderId"]
    ];

    function prop_data_after_create($_id){
    	$data = $this->get($_id);
    	$count = $this->count_by(['JobOrderType'=>$data->JobOrderType ,  'inHouse'=>$data->inHouse ]);
    	return  $this->update($_id , ['jobOrderNo' => $data->jobOrderNo."-$count" ] )? TRUE : FALSE ;
    }

    function get($primary_value)
    {
        $this->with("Customer");
        $this->with("Item");
        $this->with("Repair");
        return parent::get($primary_value); // TODO: Change the autogenerated stub
    }


}